#!/bin/bash

#./axpy [problem_size] [single|double] [divide_val] [num_threads]
#1.problem_size	:|32 | default
#2.single_double:|0. double |1. single |
#3.divide_val	:|1 |4 |8 |16 |32 |64 |128 |256 |512 |
#4.num_threads	:from 64 to 1024 with step =32

#./axpy 512 1 1 128

echo "Running..."
FOLDER="../output/axpy/"
FILENAME=""
results=""

for sp in {0..1}
do
	FILENAME="AXPY"
	if [ $sp -eq 1 ]
	then
		FILENAME1="${FILENAME}_SP"
	else
		FILENAME1="${FILENAME}_DP"
	fi
	for problem_size in 32
	do
		FILENAME="${FILENAME1}"$'_'"${problem_size}MB"
		for divide_val in 1 4 8 16 32 64 128 256 512
		do
			for num_threads in {64..1024..32}
			do
				results="${results}"$'\n'"$(./axpy $problem_size $sp $divide_val $num_threads)"
			done
		done
		echo "${results}" > "${FOLDER}""${FILENAME}"
	done
	results=""
done

